-- Step 1: Add new enum values (must be in separate transaction)
ALTER TYPE "Status" ADD VALUE IF NOT EXISTS 'WERYFIKACJA_KOMPLETNOSCI';
ALTER TYPE "Status" ADD VALUE IF NOT EXISTS 'OCZEKIWANIE_NA_PLATNOSC';
ALTER TYPE "Status" ADD VALUE IF NOT EXISTS 'W_RECENZJI';
ALTER TYPE "Status" ADD VALUE IF NOT EXISTS 'OCZEKIWANIE_NA_POPRAWKI';
ALTER TYPE "Status" ADD VALUE IF NOT EXISTS 'PONOWNA_RECENZJA';
